/**
 * 프로젝트 문서 유형별 기본 템플릿 소스 / Default template sources per project document type
 *
 * @description
 * KR: 8개 프로젝트 문서 유형 각각에 맞는 Handlebars 기본 템플릿을 제공한다.
 * EN: Provides type-specific Handlebars default templates for each of the 8 project document types.
 */

import type { ProjectDocumentType } from 'layer3/types.js';

/** 프로젝트 문서 유형별 기본 템플릿 / Default templates per project document type */
export const PROJECT_TEMPLATE_SOURCES: Record<ProjectDocumentType, string> = {
  readme: `# {{projectName}}

{{projectDescription}}

## Table of Contents

- [Features](#features)
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [License](#license)

## Features

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

## Installation

\`\`\`bash
bun install
\`\`\`

## Usage

\`\`\`bash
bun run start
\`\`\`

## Contributing

See [CONTRIBUTING.md](./CONTRIBUTING.md) for guidelines.

## License

MIT

---

Generated by adev on {{generatedAt}}
`,

  'api-reference': `# {{projectName}} — API Reference

{{projectDescription}}

## Endpoints

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

## Error Codes

| Code | Description |
|------|-------------|
| 400  | Bad Request |
| 401  | Unauthorized |
| 404  | Not Found |
| 500  | Internal Server Error |

## Authentication

All API requests require a valid API key passed via the \`Authorization\` header.

---

Generated by adev on {{generatedAt}}
`,

  architecture: `# {{projectName}} — Architecture

{{projectDescription}}

## System Overview

### Module Structure

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

## Design Decisions

Key architectural decisions are recorded in the project's decision log.

## Dependencies

Module dependency graph follows a strict unidirectional flow.

---

Generated by adev on {{generatedAt}}
`,

  'user-manual': `# {{projectName}} — User Manual

{{projectDescription}}

## Getting Started

### Prerequisites

Ensure you have the required runtime and dependencies installed.

### Quick Start

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

## Troubleshooting

### Common Issues

Check the project FAQ or open an issue if you encounter problems.

---

Generated by adev on {{generatedAt}}
`,

  'installation-guide': `# {{projectName}} — Installation Guide

{{projectDescription}}

## System Requirements

- Runtime: Bun >= 1.0
- OS: macOS, Linux, Windows (WSL)

## Installation Steps

### 1. Clone the Repository

\`\`\`bash
git clone <repository-url>
cd {{projectName}}
\`\`\`

### 2. Install Dependencies

\`\`\`bash
bun install
\`\`\`

### 3. Configure Environment

Copy \`.env.example\` to \`.env\` and fill in the required values.

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

### 4. Verify Installation

\`\`\`bash
bun test
\`\`\`

---

Generated by adev on {{generatedAt}}
`,

  'test-report': `# {{projectName}} — Test Report

{{projectDescription}}

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | — |
| Passed | — |
| Failed | — |
| Coverage | — |

## Test Results

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

## Test Categories

- **Unit Tests**: Individual function/class behavior
- **Module Tests**: Cross-module integration
- **E2E Tests**: Full system scenarios

---

Generated by adev on {{generatedAt}}
`,

  changelog: `# {{projectName}} — Changelog

{{projectDescription}}

All notable changes to this project are documented here.
This project follows [Semantic Versioning](https://semver.org/).

{{#each fragments}}
## {{id}}

{{content}}

{{/each}}

---

Generated by adev on {{generatedAt}}
`,

  'contributing-guide': `# {{projectName}} — Contributing Guide

{{projectDescription}}

## How to Contribute

1. Fork the repository
2. Create a feature branch (\`feature/your-feature\`)
3. Write tests first (TDD)
4. Implement the feature
5. Ensure all tests pass (\`bun test\`)
6. Submit a pull request

## Code Standards

- TypeScript strict mode
- Biome for linting and formatting
- Result pattern for error handling
- JSDoc for all public APIs

## Branch Naming

- \`feature/{name}\` — New features
- \`fix/{name}\` — Bug fixes
- \`refactor/{name}\` — Code refactoring

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

---

Generated by adev on {{generatedAt}}
`,
};

/** 알 수 없는 유형용 폴백 템플릿 / Fallback template for unknown types */
export const FALLBACK_TEMPLATE_SOURCE = `# {{projectName}}

{{projectDescription}}

## Features

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

---

Generated by adev on {{generatedAt}}
`;
