/**
 * layer3 문서 타입 정의 / Layer 3 document type definitions
 *
 * @description
 * KR: 문서 템플릿, 조각, 통합 문서, 협업 문서 관련 타입.
 * EN: Types for document templates, fragments, integrated docs, and collaborative docs.
 */

// ── 문서 템플릿 / Document Template ─────────────────────────────

/**
 * 프로젝트 문서 템플릿 타입 / Project document template type
 *
 * @description
 * KR: 3계층에서 생성하는 프로젝트 문서 8개 유형.
 * EN: 8 types of project documents generated in Layer 3.
 */
export type ProjectDocumentType =
  | 'readme'
  | 'api-reference'
  | 'architecture'
  | 'user-manual'
  | 'installation-guide'
  | 'test-report'
  | 'changelog'
  | 'contributing-guide';

/**
 * 비즈니스 산출물 타입 / Business deliverable type
 *
 * @description
 * KR: 3계층에서 생성하는 비즈니스 산출물 4개 유형.
 * EN: 4 types of business deliverables generated in Layer 3.
 */
export type BusinessDeliverableType =
  | 'portfolio'
  | 'business-plan'
  | 'investment-proposal'
  | 'presentation';

/**
 * 문서 출력 형식 / Document format
 */
export type DocumentFormat = 'md' | 'html' | 'pdf' | 'docx' | 'pptx';

/**
 * 문서 템플릿 / Document template
 *
 * @description
 * KR: 문서 생성에 사용되는 템플릿 정의.
 * EN: Template definition used for document generation.
 */
export interface DocumentTemplate {
  /** 템플릿 ID / Template ID */
  readonly id?: string;
  /** 템플릿 이름 / Template name */
  readonly name?: string;
  /** 문서 유형 / Document type */
  readonly type: ProjectDocumentType | BusinessDeliverableType | 'custom';
  /** 템플릿 파일 경로 / Template file path */
  readonly templatePath?: string;
  /** 출력 형식 / Output format */
  readonly format?: DocumentFormat;
  /** 템플릿 설명 / Template description */
  readonly description?: string;
  /** 커스텀 템플릿 여부 / Whether custom template */
  readonly custom?: boolean;
  /** 템플릿 제목 / Template title */
  readonly title?: string;
  /** 템플릿 섹션 목록 / Template sections */
  readonly sections?: readonly DocumentSection[];
  /** 문서 언어 / Document language */
  readonly language?: 'en' | 'ko' | 'bilingual';
}

/**
 * 문서 섹션 / Document section
 *
 * @description
 * KR: 템플릿 내 개별 섹션 정의.
 * EN: Individual section definition within template.
 */
export interface DocumentSection {
  /** 섹션 제목 / Section heading */
  readonly heading: string;
  /** 섹션 내용 / Section content */
  readonly content: string;
  /** 섹션 순서 / Section order */
  readonly order: number;
  /** 필수 섹션 여부 / Whether required */
  readonly required: boolean;
}

/**
 * 문서 조각 / Document fragment
 *
 * @description
 * KR: 2계층 documenter가 생성한 개별 조각 문서.
 * EN: Individual fragment document generated by Layer 2 documenter.
 */
export interface DocumentFragment {
  /** 조각 ID / Fragment ID */
  readonly id: string;
  /** 기능 ID / Feature ID */
  readonly featureId: string;
  /** 조각 유형 / Fragment type */
  readonly type:
    | 'feature-doc'
    | 'test-result'
    | 'api-spec'
    | 'bug-report'
    | 'changelog'
    | 'review'
    | 'decision';
  /** 조각 내용 / Fragment content */
  readonly content: string;
  /** 생성 시각 / Created at */
  readonly createdAt: Date;
  /** 메타데이터 / Metadata */
  readonly metadata: Readonly<Record<string, unknown>>;
}

// ── 통합 문서 / Integrated Document ─────────────────────────────

/**
 * 통합 문서 / Integrated document
 *
 * @description
 * KR: 여러 조각을 통합하여 생성된 최종 문서.
 * EN: Final document generated by integrating multiple fragments.
 */
export interface IntegratedDocument {
  /** 문서 ID / Document ID */
  readonly id: string;
  /** 프로젝트 ID / Project ID */
  readonly projectId: string;
  /** 문서 유형 / Document type */
  readonly type: ProjectDocumentType;
  /** 문서 내용 / Document content */
  readonly content: string;
  /** 출력 파일 경로 / Output file path */
  readonly outputPath?: string;
  /** 사용된 조각 ID 목록 / Used fragment IDs */
  readonly fragmentIds?: readonly string[];
  /** 생성 시각 / Generated at */
  readonly generatedAt: Date;
  /** 문서 버전 / Document version */
  readonly version: number;
  /** 원본 조각 문서 목록 / Source fragment documents */
  readonly sourceFragments: readonly string[];
}

// ── 협업 문서 / Collaborative Document ──────────────────────────

/**
 * 협업 문서 생성 옵션 / Collaborative document generation options
 *
 * @description
 * KR: 1계층(뼈대) + 2계층(상세) 협업 문서 생성 옵션.
 * EN: Options for collaborative document generation between Layer 1 (structure) and Layer 2 (details).
 */
export interface CollaborativeDocOptions {
  /** 프로젝트 ID / Project ID */
  readonly projectId: string;
  /** 문서 유형 / Document type */
  readonly type: ProjectDocumentType | BusinessDeliverableType;
  /** 1계층 뼈대 내용 / Layer 1 structure content */
  readonly layer1Structure: string;
  /** 2계층 조각 목록 / Layer 2 fragment list */
  readonly layer2Fragments: readonly DocumentFragment[];
  /** 출력 경로 / Output path */
  readonly outputPath: string;
}

/**
 * 협업 문서 결과 / Collaborative document result
 */
export interface CollaborativeDocResult {
  /** 문서 ID / Document ID */
  readonly id: string;
  /** 최종 내용 / Final content */
  readonly content: string;
  /** 출력 파일 경로 / Output file path */
  readonly outputPath: string;
  /** 생성 시각 / Generated at */
  readonly generatedAt: Date;
}

/**
 * 문서 유형 (통합) / Document type (unified)
 *
 * @description
 * KR: 프로젝트 문서와 비즈니스 산출물을 포괄하는 통합 타입.
 * EN: Unified type encompassing both project documents and business deliverables.
 */
export type DocumentType = ProjectDocumentType | BusinessDeliverableType;
