/**
 * 문서 조각 파싱 헬퍼 / Document fragment parsing helpers
 *
 * @description
 * KR: DocIntegrator에서 분리된 조각 문서 파싱 로직을 제공한다.
 * EN: Provides fragment document parsing logic extracted from DocIntegrator.
 */

import { Layer3Error } from 'core/errors.js';
import type { Logger } from 'core/logger.js';
import type { Result } from 'core/types.js';
import { err, ok } from 'core/types.js';
import { VALID_FRAGMENT_TYPES } from 'layer3/doc-integrator-types.js';
import type {
  DocumentFragment,
  DocumentTemplate,
  IntegratedDocument,
  ProjectDocumentType,
} from 'layer3/types.js';

export {
  integrateSync,
  integrateWithOptions,
} from 'layer3/doc-integrator-merge.js';

/**
 * 통합 문서를 YAML frontmatter가 포함된 마크다운으로 변환한다 / Convert integrated document to markdown with YAML frontmatter
 *
 * @param doc - 통합 문서 / Integrated document
 * @returns 마크다운 문자열 / Markdown string
 */
export function buildMarkdownExport(doc: IntegratedDocument): string {
  const frontmatter = [
    '---',
    `title: ${doc.content.match(/^# (.+)$/m)?.[1] ?? doc.id}`,
    `version: ${doc.version}`,
    `projectId: ${doc.projectId}`,
    'language: bilingual',
    `generatedAt: ${doc.generatedAt.toISOString()}`,
    '---',
  ].join('\n');

  return `${frontmatter}\n\n${doc.content}`;
}

/**
 * 기존 통합 문서에 새 조각을 추가하여 업데이트한다 / Update integrated document by appending new fragments
 *
 * @param doc - 기존 통합 문서 / Existing integrated document
 * @param newFragments - 새 조각 목록 / New fragment list
 * @returns 업데이트된 통합 문서 결과 / Updated integrated document result
 */
export function buildUpdatedDocument(
  doc: IntegratedDocument,
  newFragments: readonly string[],
): Result<IntegratedDocument, Layer3Error> {
  if (!newFragments || newFragments.length === 0) {
    return err(new Layer3Error('layer3_empty_fragments', '새 조각 문서 목록이 비어 있습니다'));
  }

  // WHY: 기존 조각에 새 조각 추가 + 업데이트 부록 내용 추가
  const allFragments = [...doc.sourceFragments, ...newFragments];
  const updatedContent = `${doc.content}\n\n## 업데이트 부록\n\n새로운 조각이 추가되었습니다.`;

  return ok({
    ...doc,
    version: doc.version + 1,
    sourceFragments: allFragments,
    content: updatedContent,
    generatedAt: new Date(),
  });
}

/**
 * 내장 기본 템플릿 소스를 반환한다 / Return built-in default template source
 *
 * @param _type - 문서 유형 / Document type (reserved for future per-type templates)
 * @returns 기본 템플릿 소스 / Default template source
 */
export function getDefaultTemplateSource(_type: ProjectDocumentType | string): string {
  return `# {{projectName}}

{{projectDescription}}

## Features

{{#each fragments}}
### {{id}}

{{content}}

{{/each}}

---

Generated by adev on {{generatedAt}}
`;
}

/**
 * 템플릿 파일에서 Handlebars 소스를 읽는다 / Read Handlebars template source from file
 *
 * @description
 * KR: Bun.file().text()로 실제 템플릿 파일을 읽는다. 파일이 없으면 내장 기본 템플릿을 사용한다.
 * EN: Reads actual template file with Bun.file().text(). Falls back to built-in default if file not found.
 *
 * @param template - 템플릿 정의 / Template definition
 * @param logger - 로거 / Logger
 * @returns 템플릿 소스 문자열 / Template source string
 */
export async function readTemplateSourceFile(
  template: DocumentTemplate,
  logger: Logger,
): Promise<string> {
  if (template.templatePath) {
    try {
      const templateFile = Bun.file(template.templatePath);
      const exists = await templateFile.exists();
      if (exists) {
        const source = await templateFile.text();
        logger.debug('템플릿 파일 읽기 완료', {
          templatePath: template.templatePath,
          length: source.length,
        });
        return source;
      }
    } catch (readError) {
      logger.warn('템플릿 파일 읽기 실패, 기본 템플릿 사용', {
        templatePath: template.templatePath,
        error: readError instanceof Error ? readError.message : String(readError),
      });
    }
  }

  // WHY: 파일이 없거나 읽기 실패 시 내장 기본 템플릿 반환
  return getDefaultTemplateSource(template.type);
}

/**
 * 마크다운 파일에서 DocumentFragment를 파싱한다 / Parse DocumentFragment from a markdown file
 *
 * @description
 * KR: YAML frontmatter (--- 구분자 사이) 에서 id, featureId, type 등을 추출하고,
 *     본문을 content로 사용한다. frontmatter가 없으면 파일명 기반 기본값 사용.
 * EN: Extracts id, featureId, type from YAML frontmatter (between --- delimiters),
 *     uses body as content. Falls back to filename-based defaults if no frontmatter.
 *
 * @param filePath - 파일 경로 / File path
 * @param text - 파일 내용 / File content
 * @returns DocumentFragment 또는 null / DocumentFragment or null
 */
export function parseFragmentFromMarkdown(filePath: string, text: string): DocumentFragment | null {
  const trimmed = text.trim();
  if (!trimmed) {
    return null;
  }

  // WHY: YAML frontmatter 파싱 — "---\n...\n---" 사이의 내용 추출
  const frontmatterMatch = trimmed.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);

  let id = filePath;
  let featureId = 'unknown';
  let fragmentType: DocumentFragment['type'] = 'feature-doc';
  let content = trimmed;
  const metadata: Record<string, unknown> = {};

  if (frontmatterMatch) {
    const yamlBlock = frontmatterMatch[1] ?? '';
    content = (frontmatterMatch[2] ?? '').trim();

    // WHY: 간단한 key: value YAML 파싱 (외부 라이브러리 없이)
    for (const line of yamlBlock.split('\n')) {
      const colonIdx = line.indexOf(':');
      if (colonIdx === -1) {
        continue;
      }
      const key = line.slice(0, colonIdx).trim();
      const value = line.slice(colonIdx + 1).trim();

      switch (key) {
        case 'id':
          id = value;
          break;
        case 'featureId':
        case 'feature_id':
          featureId = value;
          break;
        case 'type':
          if (VALID_FRAGMENT_TYPES.has(value)) {
            fragmentType = value as DocumentFragment['type'];
          }
          break;
        default:
          metadata[key] = value;
          break;
      }
    }
  }

  return {
    id,
    featureId,
    type: fragmentType,
    content,
    createdAt: new Date(),
    metadata,
  };
}
