/**
 * 프로젝트 scaffold 로직 / Project scaffold logic
 *
 * @description
 * KR: .adev/ 디렉토리 구조 자동 생성과 기본 에이전트 템플릿 생성을 담당한다.
 * EN: Handles .adev/ directory structure auto-creation and default agent template generation.
 */

import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Logger } from 'core/logger.js';

/** 7개 기본 에이전트 이름 / Default agent names */
const DEFAULT_AGENT_NAMES = [
  'architect',
  'qa',
  'coder',
  'tester',
  'qc',
  'reviewer',
  'documenter',
] as const;

/**
 * 기본 agent.md 템플릿 / Default agent.md template
 */
function getDefaultAgentTemplate(agentName: string): string {
  return `# ${agentName} Agent

## 역할 / Role

${agentName} 에이전트의 역할을 정의합니다.

## 책임 / Responsibilities

- 주요 책임 1
- 주요 책임 2

## 시스템 프롬프트 / System Prompt

이 에이전트의 시스템 프롬프트를 작성합니다.

## 도구 / Tools

사용 가능한 도구 목록:
- tool1
- tool2

---

Generated by adev project add
`;
}

/**
 * .adev/ 프로젝트 디렉토리 완전 자동 scaffold / Full auto-scaffold .adev/ project directories
 *
 * @description
 * KR: 프로젝트 등록(add) 시 .adev/ 전체 디렉토리 구조를 자동 생성한다.
 *     config.json, data/memory/, data/code-index/, agents/(7개 md),
 *     sessions/, mcp/, skills/, templates/ 를 생성한다.
 * EN: Auto-creates full .adev/ directory structure on project add.
 *     Creates config.json, data directories, 7 agent.md files, and subdirectories.
 *
 * @param projectPath - 프로젝트 루트 경로 / Project root path
 * @param logger - 로거 / Logger
 */
export async function scaffoldProjectDirectories(
  projectPath: string,
  logger: Logger,
): Promise<void> {
  const adevPath = join(projectPath, '.adev');

  // WHY: init-scaffold.ts의 디렉토리 구조와 동일하게 맞춤
  const directories = [
    adevPath,
    join(adevPath, 'data'),
    join(adevPath, 'data', 'memory'),
    join(adevPath, 'data', 'code-index'),
    join(adevPath, 'agents'),
    join(adevPath, 'sessions'),
    join(adevPath, 'mcp'),
    join(adevPath, 'skills'),
    join(adevPath, 'templates'),
  ] as const;

  for (const dir of directories) {
    try {
      await mkdir(dir, { recursive: true });
    } catch {
      logger.warn('.adev/ 디렉토리 생성 실패', { dir, projectPath });
    }
  }

  // WHY: 기본 config.json 생성 — init-scaffold.ts와 동일 구조
  const configPath = join(adevPath, 'config.json');
  if (!existsSync(configPath)) {
    try {
      const defaultConfig = {
        log: { level: 'info' },
        embedding: { default: 'xenova-minilm' },
        testing: { bail: true },
        verification: { layer1Model: 'opus' },
      };
      await writeFile(configPath, JSON.stringify(defaultConfig, null, 2), 'utf-8');
    } catch {
      logger.warn('config.json 생성 실패', { configPath });
    }
  }

  // WHY: 7개 기본 agent.md 파일 생성 — 이미 있으면 건너뜀
  const agentsPath = join(adevPath, 'agents');
  for (const agentName of DEFAULT_AGENT_NAMES) {
    const agentFilePath = join(agentsPath, `${agentName}.md`);
    if (existsSync(agentFilePath)) continue;
    try {
      await writeFile(agentFilePath, getDefaultAgentTemplate(agentName), 'utf-8');
    } catch {
      logger.warn('agent.md 생성 실패', { agentName, agentFilePath });
    }
  }

  logger.debug('.adev/ scaffold 완료', {
    projectPath,
    dirCount: directories.length,
    agentCount: DEFAULT_AGENT_NAMES.length,
  });
}
