/**
 * 프로젝트 CRUD 로직 / Project CRUD logic
 *
 * @description
 * KR: 프로젝트 add/remove/switch/update 핸들러를 담당한다.
 * EN: Handles project add/remove/switch/update operations.
 */

import { existsSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { createInterface } from 'node:readline';
import { loadRegistry, saveRegistry } from 'cli/commands/project-registry.js';
import type { ProjectInfo, ProjectOptions, ProjectRegistry } from 'cli/types.js';
import { AdevError } from 'core/errors.js';
import type { Logger } from 'core/logger.js';
import { err, ok } from 'core/types.js';
import type { Result } from 'core/types.js';

/** 7개 기본 에이전트 이름 / Default agent names */
const DEFAULT_AGENT_NAMES = [
  'architect',
  'qa',
  'coder',
  'tester',
  'qc',
  'reviewer',
  'documenter',
] as const;

/**
 * 기본 agent.md 템플릿 / Default agent.md template
 */
function getDefaultAgentTemplate(agentName: string): string {
  return `# ${agentName} Agent

## 역할 / Role

${agentName} 에이전트의 역할을 정의합니다.

## 책임 / Responsibilities

- 주요 책임 1
- 주요 책임 2

## 시스템 프롬프트 / System Prompt

이 에이전트의 시스템 프롬프트를 작성합니다.

## 도구 / Tools

사용 가능한 도구 목록:
- tool1
- tool2

---

Generated by adev project add
`;
}

/**
 * .adev/ 프로젝트 디렉토리 완전 자동 scaffold / Full auto-scaffold .adev/ project directories
 *
 * @description
 * KR: 프로젝트 등록(add) 시 .adev/ 전체 디렉토리 구조를 자동 생성한다.
 *     config.json, data/memory/, data/code-index/, agents/(7개 md),
 *     sessions/, mcp/, skills/, templates/ 를 생성한다.
 * EN: Auto-creates full .adev/ directory structure on project add.
 *     Creates config.json, data directories, 7 agent.md files, and subdirectories.
 *
 * @param projectPath - 프로젝트 루트 경로 / Project root path
 * @param logger - 로거 / Logger
 */
async function scaffoldProjectDirectories(projectPath: string, logger: Logger): Promise<void> {
  const adevPath = join(projectPath, '.adev');

  // WHY: init-scaffold.ts의 디렉토리 구조와 동일하게 맞춤
  const directories = [
    adevPath,
    join(adevPath, 'data'),
    join(adevPath, 'data', 'memory'),
    join(adevPath, 'data', 'code-index'),
    join(adevPath, 'agents'),
    join(adevPath, 'sessions'),
    join(adevPath, 'mcp'),
    join(adevPath, 'skills'),
    join(adevPath, 'templates'),
  ] as const;

  for (const dir of directories) {
    try {
      await mkdir(dir, { recursive: true });
    } catch {
      logger.warn('.adev/ 디렉토리 생성 실패', { dir, projectPath });
    }
  }

  // WHY: 기본 config.json 생성 — init-scaffold.ts와 동일 구조
  const configPath = join(adevPath, 'config.json');
  if (!existsSync(configPath)) {
    try {
      const defaultConfig = {
        log: { level: 'info' },
        embedding: { default: 'xenova-minilm' },
        testing: { bail: true },
        verification: { layer1Model: 'opus' },
      };
      await writeFile(configPath, JSON.stringify(defaultConfig, null, 2), 'utf-8');
    } catch {
      logger.warn('config.json 생성 실패', { configPath });
    }
  }

  // WHY: 7개 기본 agent.md 파일 생성 — 이미 있으면 건너뜀
  const agentsPath = join(adevPath, 'agents');
  for (const agentName of DEFAULT_AGENT_NAMES) {
    const agentFilePath = join(agentsPath, `${agentName}.md`);
    if (existsSync(agentFilePath)) continue;
    try {
      await writeFile(agentFilePath, getDefaultAgentTemplate(agentName), 'utf-8');
    } catch {
      logger.warn('agent.md 생성 실패', { agentName, agentFilePath });
    }
  }

  logger.debug('.adev/ scaffold 완료', {
    projectPath,
    dirCount: directories.length,
    agentCount: DEFAULT_AGENT_NAMES.length,
  });
}

/**
 * 중복 프로젝트 처리 결과 / Duplicate project resolution result
 *
 * @description
 * KR: 이름 중복 시 반환되는 구조화된 에러. duplicateAction 필드로 호출 측이
 *     '다른 이름 / 기존 업데이트 / 취소' 선택지를 유저에게 제시할 수 있다.
 * EN: Structured error returned on name collision. The duplicateAction field
 *     enables the caller to present 'rename / update / cancel' options to the user.
 */
export interface DuplicateProjectInfo {
  readonly existingName: string;
  readonly existingPath: string;
  readonly suggestedActions: readonly ['rename', 'update', 'cancel'];
}

/**
 * 프로젝트 CRUD 핸들러 / Project CRUD handler
 *
 * @description
 * KR: 프로젝트 등록, 삭제, 전환, 수정 로직을 담당한다.
 * EN: Handles project registration, removal, switching, and updating logic.
 */
export class ProjectCrudHandler {
  private readonly logger: Logger;
  private readonly registryDir: string;

  constructor(logger: Logger, registryDir: string) {
    this.logger = logger;
    this.registryDir = registryDir;
  }

  /**
   * project add <path>: 프로젝트 등록 / Register a project
   *
   * @param args - CLI 인자 / CLI arguments
   * @returns 성공 시 ok(void), 실패 시 err(AdevError)
   */
  async handleAdd(args: readonly string[]): Promise<Result<void, AdevError>> {
    const rawPath = args[0];
    if (!rawPath) {
      return err(
        new AdevError('cli_project_missing_path', 'project add: 프로젝트 경로를 지정하세요'),
      );
    }

    const projectPath = resolve(rawPath);
    const projectName = basename(projectPath);

    const registryResult = await loadRegistry(this.registryDir);
    if (!registryResult.ok) {
      return err((registryResult as Extract<typeof registryResult, { ok: false }>).error);
    }

    const registry = registryResult.value;

    // WHY: 중복 등록 방지 -- 이름 또는 경로가 같은 프로젝트가 있는지 확인
    const duplicate = registry.projects.find(
      (p) => p.name === projectName || p.path === projectPath,
    );
    if (duplicate) {
      // WHY: PI-012 — TTY 환경에서는 3선택지 인터랙티브 UI를 제공한다
      if (process.stdin.isTTY && process.stdout.isTTY) {
        const choice = await this.promptDuplicateAction(duplicate.name);

        if (choice === 'rename') {
          // WHY: 다른 이름으로 재등록 — 새 이름을 입력받아 재귀 호출 대신 직접 등록
          const newName = await this.promptNewName();
          if (!newName) {
            return err(new AdevError('cli_project_cancelled', '프로젝트 등록이 취소되었습니다'));
          }
          // WHY: 새 이름으로 등록 진행 (아래 등록 로직에서 projectName 대신 newName 사용)
          return this.registerProject(newName, projectPath, registry);
        }

        if (choice === 'update') {
          // WHY: 기존 프로젝트의 경로를 업데이트한다
          const updatedProjects = registry.projects.map((p) =>
            p.name === duplicate.name ? { ...p, path: projectPath, lastAccessedAt: new Date() } : p,
          );
          const updatedRegistry: ProjectRegistry = {
            activeProject: registry.activeProject,
            projects: updatedProjects,
          };
          const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
          if (!saveResult.ok) return saveResult;
          this.logger.info('기존 프로젝트 업데이트 완료', {
            name: duplicate.name,
            path: projectPath,
          });
          return ok(undefined);
        }

        // WHY: cancel 선택
        return err(new AdevError('cli_project_cancelled', '프로젝트 등록이 취소되었습니다'));
      }

      // WHY: non-TTY 환경에서는 구조화된 에러로 반환
      const duplicateInfo: DuplicateProjectInfo = {
        existingName: duplicate.name,
        existingPath: duplicate.path,
        suggestedActions: ['rename', 'update', 'cancel'],
      };
      const error = new AdevError(
        'cli_project_duplicate',
        `이미 등록된 프로젝트입니다: '${duplicate.name}' (${duplicate.path}). ` +
          '선택: 1) 다른 이름으로 등록 (rename) 2) 기존 업데이트 (update) 3) 취소 (cancel)',
      );
      // WHY: cause에 구조화된 정보를 첨부하여 CLI 레이어에서 파싱 가능
      (error as AdevError & { duplicateInfo: DuplicateProjectInfo }).duplicateInfo = duplicateInfo;
      return err(error);
    }

    const now = new Date();
    const projectId = crypto.randomUUID();
    const newProject: ProjectInfo = {
      id: projectId,
      name: projectName,
      path: projectPath,
      createdAt: now,
      lastAccessedAt: now,
      status: 'active',
    };

    const updatedRegistry: ProjectRegistry = {
      activeProject: registry.activeProject ?? projectName,
      projects: [...registry.projects, newProject],
    };

    const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
    if (!saveResult.ok) return saveResult;

    // WHY: 프로젝트 등록 시 .adev/ 서브디렉토리를 자동 scaffold (PI-006)
    await scaffoldProjectDirectories(projectPath, this.logger);

    this.logger.info('프로젝트 등록 완료 / Project registered', {
      name: projectName,
      path: projectPath,
    });
    return ok(undefined);
  }

  /**
   * 중복 시 3선택지 인터랙티브 프롬프트 / Interactive prompt for duplicate resolution
   *
   * @param existingName - 기존 프로젝트 이름 / Existing project name
   * @returns 선택된 액션 / Selected action
   */
  private async promptDuplicateAction(
    existingName: string,
  ): Promise<'rename' | 'update' | 'cancel'> {
    process.stdout.write(`\n프로젝트 이름 '${existingName}'이 이미 존재합니다.\n`);
    process.stdout.write('  1) 다른 이름 입력\n');
    process.stdout.write('  2) 기존 프로젝트 업데이트\n');
    process.stdout.write('  3) 취소\n');
    process.stdout.write('선택 (1-3, 기본값: 3): ');

    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const input = await new Promise<string>((resolve) => {
      rl.once('line', (line) => {
        rl.close();
        resolve(line.trim());
      });
    });

    if (input === '1') return 'rename';
    if (input === '2') return 'update';
    return 'cancel';
  }

  /**
   * 새 프로젝트 이름을 입력받는다 / Prompts for a new project name
   *
   * @returns 입력된 이름 또는 null / Entered name or null
   */
  private async promptNewName(): Promise<string | null> {
    process.stdout.write('새 프로젝트 이름을 입력하세요 (엔터=취소): ');

    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const input = await new Promise<string>((resolve) => {
      rl.once('line', (line) => {
        rl.close();
        resolve(line.trim());
      });
    });

    return input || null;
  }

  /**
   * 프로젝트를 레지스트리에 등록한다 / Registers a project to the registry
   *
   * @param projectName - 프로젝트 이름 / Project name
   * @param projectPath - 프로젝트 경로 / Project path
   * @param registry - 현재 레지스트리 / Current registry
   * @returns 성공 시 ok(void), 실패 시 err(AdevError)
   */
  private async registerProject(
    projectName: string,
    projectPath: string,
    registry: ProjectRegistry,
  ): Promise<Result<void, AdevError>> {
    const now = new Date();
    const projectId = crypto.randomUUID();
    const newProject: ProjectInfo = {
      id: projectId,
      name: projectName,
      path: projectPath,
      createdAt: now,
      lastAccessedAt: now,
      status: 'active',
    };

    const updatedRegistry: ProjectRegistry = {
      activeProject: registry.activeProject ?? projectName,
      projects: [...registry.projects, newProject],
    };

    const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
    if (!saveResult.ok) return saveResult;

    await scaffoldProjectDirectories(projectPath, this.logger);

    this.logger.info('프로젝트 등록 완료 / Project registered', {
      name: projectName,
      path: projectPath,
    });
    return ok(undefined);
  }

  /**
   * project remove <name>: 프로젝트 삭제 / Unregister a project
   *
   * @param args - CLI 인자 / CLI arguments
   * @param options - CLI 옵션 / CLI options
   * @returns 성공 시 ok(void), 실패 시 err(AdevError)
   */
  async handleRemove(
    args: readonly string[],
    options: ProjectOptions,
  ): Promise<Result<void, AdevError>> {
    const projectName = args[0];
    if (!projectName) {
      return err(
        new AdevError('cli_project_missing_name', 'project remove: 프로젝트 이름을 지정하세요'),
      );
    }

    const deleteData = options.deleteData === true;

    const registryResult = await loadRegistry(this.registryDir);
    if (!registryResult.ok) {
      return err((registryResult as Extract<typeof registryResult, { ok: false }>).error);
    }

    const registry = registryResult.value;
    const target = registry.projects.find((p) => p.name === projectName);

    if (!target) {
      return err(
        new AdevError('cli_project_not_found', `프로젝트를 찾을 수 없습니다: '${projectName}'`),
      );
    }

    // WHY: --delete-data 플래그가 있으면 .adev/ 디렉토리도 삭제
    if (deleteData) {
      this.logger.warn('경고: .adev/ 디렉토리를 삭제합니다', {
        projectPath: target.path,
      });

      try {
        const adevDir = resolve(target.path, '.adev');
        if (existsSync(adevDir)) {
          await rm(adevDir, { recursive: true, force: true });
          this.logger.info('.adev/ 디렉토리 삭제됨', { path: adevDir });
        }
      } catch (error: unknown) {
        this.logger.error('.adev/ 디렉토리 삭제 실패', { error: String(error) });
        // WHY: 디렉토리 삭제 실패해도 레지스트리에서는 제거
      }
    }

    const filtered = registry.projects.filter((p) => p.name !== projectName);

    const updatedRegistry: ProjectRegistry = {
      activeProject:
        registry.activeProject === target.name
          ? (filtered[0]?.name ?? null)
          : registry.activeProject,
      projects: filtered,
    };

    const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
    if (!saveResult.ok) return saveResult;

    this.logger.info('프로젝트 삭제 완료 / Project removed', {
      name: projectName,
      deletedData: deleteData,
    });
    return ok(undefined);
  }

  /**
   * project switch <name>: 활성 프로젝트 전환 / Switch active project
   *
   * @param args - CLI 인자 / CLI arguments
   * @returns 성공 시 ok(void), 실패 시 err(AdevError)
   */
  async handleSwitch(args: readonly string[]): Promise<Result<void, AdevError>> {
    const projectName = args[0];
    if (!projectName) {
      return err(
        new AdevError('cli_project_missing_name', 'project switch: 프로젝트 이름을 지정하세요'),
      );
    }

    const registryResult = await loadRegistry(this.registryDir);
    if (!registryResult.ok) {
      return err((registryResult as Extract<typeof registryResult, { ok: false }>).error);
    }

    const registry = registryResult.value;
    const target = registry.projects.find((p) => p.name === projectName);

    if (!target) {
      return err(
        new AdevError('cli_project_not_found', `프로젝트를 찾을 수 없습니다: '${projectName}'`),
      );
    }

    const updatedRegistry: ProjectRegistry = {
      activeProject: target.name,
      projects: registry.projects.map((p) =>
        p.name === projectName ? { ...p, lastAccessedAt: new Date() } : p,
      ),
    };

    const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
    if (!saveResult.ok) return saveResult;

    this.logger.info('활성 프로젝트 전환 / Active project switched', {
      name: projectName,
      path: target.path,
    });
    return ok(undefined);
  }

  /**
   * project update <name>: 프로젝트 정보 수정 / Update project info
   *
   * @param args - CLI 인자 / CLI arguments
   * @param options - CLI 옵션 / CLI options
   * @returns 성공 시 ok(void), 실패 시 err(AdevError)
   */
  async handleUpdate(
    args: readonly string[],
    options: ProjectOptions,
  ): Promise<Result<void, AdevError>> {
    const projectName = args[0];
    if (!projectName) {
      return err(
        new AdevError('cli_project_missing_name', 'project update: 프로젝트 이름을 지정하세요'),
      );
    }

    const newName = options.name;
    if (!newName) {
      return err(
        new AdevError(
          'cli_project_missing_update_field',
          'project update: --name 플래그를 지정하세요',
        ),
      );
    }

    const registryResult = await loadRegistry(this.registryDir);
    if (!registryResult.ok) {
      return err((registryResult as Extract<typeof registryResult, { ok: false }>).error);
    }

    const registry = registryResult.value;
    const targetIndex = registry.projects.findIndex((p) => p.name === projectName);

    if (targetIndex === -1) {
      return err(
        new AdevError('cli_project_not_found', `프로젝트를 찾을 수 없습니다: '${projectName}'`),
      );
    }

    // WHY: 새 이름이 이미 사용 중인지 확인
    const duplicateName = registry.projects.some(
      (p, idx) => idx !== targetIndex && p.name === newName,
    );

    if (duplicateName) {
      return err(
        new AdevError(
          'cli_project_duplicate_name',
          `이미 사용 중인 프로젝트 이름입니다: '${newName}'`,
        ),
      );
    }

    const target = registry.projects[targetIndex];
    if (!target) {
      return err(
        new AdevError('cli_project_not_found', `프로젝트를 찾을 수 없습니다: '${projectName}'`),
      );
    }

    const updatedProjects = [...registry.projects];
    updatedProjects[targetIndex] = {
      ...target,
      name: newName,
    };

    const updatedRegistry: ProjectRegistry = {
      activeProject: registry.activeProject === projectName ? newName : registry.activeProject,
      projects: updatedProjects,
    };

    const saveResult = await saveRegistry(updatedRegistry, this.registryDir);
    if (!saveResult.ok) return saveResult;

    this.logger.info('프로젝트 정보 수정 완료 / Project info updated', {
      oldName: projectName,
      newName,
      path: target.path,
    });
    return ok(undefined);
  }
}
